### ISSUE TITLE
Python Code Snippet Bugs

### ISSUE THREAD

**Issue by fhightower** [ThreatConnect-Inc/ThreatConnect_Developer_Docs#162]
try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

adversaries = tc.adversaries()

adversary = adversaries.add('', owner)
adversary.set_id(20)

try:
    adversary.delete()
except RuntimeError as e:
    print(e)
    sys.exit(1)

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    adversary = adversaries.add('', owner)
NameError: name 'owner' is not defined

-------

try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

documents = tc.documents()

owner = '<Test Community>'
document = documents.add('New Document', owner)
document.set_file_name('New File.txt')

fh = open('./sample1.zip', 'rb')
contents = fh.read()
document.upload(contents)

document.add_attribute('Description', 'Description Example')
document.add_tag('EXAMPLE')
document.set_security_label('TLP Green')
try:
    document.commit()
except RuntimeError as e:
    print('Error: {0}'.format(e))
    sys.exit(1)

Traceback (most recent call last):
  File "test.py", line 30, in <module>
    fh = open('./sample1.zip', 'rb')
IOError: [Errno 2] No such file or directory: './sample1.zip'

-------

try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

documents = tc.documents()

document = documents.add('', owner)
document.set_id(20)

try:
    document.delete()
except RuntimeError as e:
    print(e)

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    document = documents.add('', owner)
NameError: name 'owner' is not defined

-------

try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

emails = tc.emails()

email = emails.add('', owner)
email.set_id(20)

try:
    email.delete()
except RuntimeError as e:
    print(e)
    sys.exit(1)

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    email = emails.add('', owner)
NameError: name 'owner' is not defined

-------

try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

incidents = tc.incidents()

incident = incidents.add('', owner)
incident.set_id(20)

try:
    incident.delete()
except RuntimeError as e:
    print(e)
    sys.exit(1)

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    incident = incidents.add('', owner)
NameError: name 'owner' is not defined

-------

try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

signatures = tc.signatures()

signature = signatures.add('', owner)
signature.set_id(20)

try:
    signature.delete()
except RuntimeError as e:
    print(e)
    sys.exit(1)

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    signature = signatures.add('', owner)
NameError: name 'owner' is not defined

-------

try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

threats = tc.threats()

threat = threats.add('', owner)
threat.set_id(20)

try:
    threat.delete()
except RuntimeError as e:
    print(e)
    sys.exit(1)

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    threat = threats.add('', owner)
NameError: name 'owner' is not defined

-------

dst_tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

\#
\# 
try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1) populate 'indicators' list of dictionaries
try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)
\#

batch_job_ids = []
batch_jobs = dst_tc.batch_jobs()
batch_job = batch_jobs.add()

batch_job.set_halt_on_error(False)             \# If True, abort processing after first error
batch_job.set_attribute_write_type('Replace')  \# Replace attributes (can also be Append)
batch_job.set_action('Create')                 \# Create indicators (can also be Delete)
batch_job.set_owner(dst_owner)                 \# Owner to write indicators to

batch_job.upload(json.dumps(indicators))

try:
    batch_job.commit()
    print("Created batchjob %s" % batch_job.id)
    batch_job_ids.append(batch_job.id)
except RuntimeError as re:
    print("Encountered problem creating batchJob")
    traceback.print_exc(file=sys.stderr)

finished_batches = []
total_time = 0
while len(batch_job_ids) > 0:
    time.sleep(args.poll_time)
    total_time += args.poll_time
    print("polling (total wait time {0} minutes)
try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)".format(int(total_time / 60)))

    batch_jobs = dst_tc.batch_jobs()
    for batchId in batch_job_ids:
        filter = batch_jobs.add_filter()
        filter.add_id(batchId)
        batch_jobs.retrieve()

        for batch_job in batch_jobs:
            if batch_job.status == 'Completed':
                finished_batches.append(batch_job)
                batch_job_ids.remove(batchId)
                print("Finished batch job {0}: succeeded: {1}, "
                      "failed: {2}, unprocessed: {3}".format(batchId, batch_job.success_count, batch_job.error_count, batch_job.unprocess_count))

success_total = 0
error_total = 0
unprocess_total = 0
for batch_job in finished_batches:
    if batch_job.unprocess_count:
        success_total += batch_job.success_count
    if batch_job.unprocess_count:
        unprocess_total += batch_job.unprocess_count
    if batch_job.unprocess_count:
        error_total += batch_job.error_count
        batch_job.download_errors()
        for error in batch_job.errors:
            print("Batch Job {0} errors: {1}".format(batch_job.id, batch_job.errors))
print("All batch jobs completed, totals:  "
      "succeeded: {0}, failed: {1}, unprocessed: {2}".format(success_total, error_total, unprocess_total))

  File "test.py", line 23
    sys.exit(1) populate 'indicators' list of dictionaries
                       ^
SyntaxError: invalid syntax

-------

try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

tasks = tc.tasks()

task = tasks.add('', owner)
task.set_id(20)

try:
    task.delete()
except RuntimeError as e:
    print(e)
    sys.exit(1)

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    task = tasks.add('', owner)
NameError: name 'owner' is not defined

-------

from threatconnect.Config.ResourceType import ResourceType

try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

victims = tc.victims()

owner = '<Test Community>'
victim = victims.add('Robin Scherbatsky', owner)

victim.set_nationality('Canadian')
victim.set_org('Royal Canadian Mounted Police')
victim.set_suborg('Quebec Office')
victim.set_work_location('Quebec')

\# email address assets can be added to new victim
asset = VictimAssetObject(ResourceType.VICTIM_EMAIL_ADDRESSES)
asset.set_address('victim@victimsareus.com')
asset.set_address_type('Personal')
victim.add_asset(asset)

\# network account assets can be added to new victim
asset = VictimAssetObject(ResourceType.VICTIM_NETWORK_ACCOUNTS)
asset.set_account('victim')
asset.set_network('victimsareus Active Directory')
victim.add_asset(asset)

\# phone assets can be added to new victim
asset = VictimAssetObject(ResourceType.VICTIM_PHONES)
asset.set_phone_type('555-555-5555')
victim.add_asset(asset)

\# social network assets can be added to new victim
asset = VictimAssetObject(ResourceType.VICTIM_SOCIAL_NETWORKS)
asset.set_account('@victim')
asset.set_network('Twitter')
victim.add_asset(asset)

\# website assets can be added to new victim
asset = VictimAssetObject(ResourceType.VICTIM_WEBSITES)
asset.set_website('www.victimsareus.com')
victim.add_asset(asset)

try:
    victim.commit()
except RuntimeError as e:
    print('Error: {0}'.format(e))
    sys.exit(1)

Traceback (most recent call last):
  File "test.py", line 37, in <module>
    asset = VictimAssetObject(ResourceType.VICTIM_EMAIL_ADDRESSES)
NameError: name 'VictimAssetObject' is not defined

-------

from threatconnect.Config.FilterOperator import FilterSetOperator
from threatconnect.Config.IndicatorType import IndicatorType

owner = '<Test Community>'

try:
    filter1 = indicators.add_filter()
    filter1.add_owner(owner)
    filter1.add_security_label('TLP Red')
except AttributeError as e:
    print(e)
    sys.exit(1)

try:
    filter2 = indicators.add_filter()
    filter2.add_owner(owner)
    filter2.add_filter_operator(FilterSetOperator.AND)
    filter2.add_threat_id(38)
except AttributeError as e:
    print(e)
    sys.exit(1)

try:
    filter3 = indicators.add_filter(IndicatorType.ADDRESSES)
    filter3.add_owner(owner)
    filter3.add_filter_operator(FilterSetOperator.OR)
    filter3.add_tag('EXAMPLE')
except AttributeError as e:
    print(e)
    sys.exit(1)

\# add code here
try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    filter1 = indicators.add_filter()
NameError: name 'indicators' is not defined

-------

try:
    import ConfigParser
except:
    import configparser as ConfigParser
import sys

from threatconnect import ThreatConnect

config = ConfigParser.RawConfigParser()
config.read("./tc.conf")

try:
    api_access_id = config.get('threatconnect', 'api_access_id')
    api_secret_key = config.get('threatconnect', 'api_secret_key')
    api_default_org = config.get('threatconnect', 'api_default_org')
    api_base_url = config.get('threatconnect', 'api_base_url')
except ConfigParser.NoOptionError:
    print('Could not read configuration file.')
    sys.exit(1)

tc = ThreatConnect(api_access_id, api_secret_key, api_default_org, api_base_url)

ro = RequestObject()
ro.set_http_method('GET')
ro.set_owner('Example Community')
ro.set_owner_allowed(True)
ro.set_resource_pagination(True)
ro.set_request_uri('/v2/indicators')

results = tc.api_request(ro)
if results.headers['content-type'] == 'application/json':
    data = results.json()
    print(json.dumps(data, indent=4))

Traceback (most recent call last):
  File "test.py", line 24, in <module>
    ro = RequestObject()
NameError: name 'RequestObject' is not defined

**Comment by fhightower** [comment]
Most of these are addresses with 98debff9ec7a423b50e1e9496e30f57de1726cb4
